name: Auto Rclone Move

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  watch:
    types: [started]
  release:
    types: [published]
  push:
    tags:
    - 'v*'

env:
  password: ${{ secrets.P_WD }}
  SSH_ACTIONS: false
  filepath: /home/runner/work/AutoRclone-Move/AutoRclone-Move
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install
      run: |
        sudo -E apt-get -qq install unzip curl wget git
        sudo curl https://rclone.org/install.sh | sudo bash

    - name: unzip
      run: |
        sudo unzip $filepath/fclone.zip -d /usr/bin
        sudo chmod 0755 /usr/bin/fclone
        sudo unzip -P $password $filepath/sa.zip -d /
        sudo unzip -P $password $filepath/rclone.zip -d /home/runner/.config/rclone
 
    - name: SSH connection to Actions
      uses: hunter-sn/debugger-action@master
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')    #env.SSH_ACTIONS == 'true'
    
    - name: rclone command
      run: |
        sudo rclone sync card-gr:Card/福利/写真套图 250:福利/写真套图 --transfers 64 --checkers 64 -P
    
