name: Auto Rclone Move

on:
  repository_dispatch:
  watch:
    types: [started]
  release:
    types: [published]
  push:
    tags:
    - 'v*'

env:
  password: ${{ secrets.P_WD }}
#  SSH_ACTIONS: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install
      run: |
        sudo -E apt-get -qq install unzip curl wget git tmate
        sudo curl https://rclone.org/install.sh | sudo bash
#        sudo bash installfclone.sh

    - name: SSH connection to Actions
#      uses: hunter-sn/debugger-action@master
#      if: env.SSH_ACTIONS == 'true'
      run: |
        sudo tmate
