name: Auto Rclone Move

on:
  repository_dispatch:
  watch:
    types: [started]
  release:
    types: [published]
  push:
    tags:
    - 'v*'

env:
  password: ${{ secrets.P_WD }}
  SSH_ACTIONS: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install
      run: |
        sudo -E apt-get -qq install unzip curl wget git
        sudo curl https://rclone.org/install.sh | sudo bash
        sudo wget -qO- https://github.com/mawaya/rclone/releases/download/fclone-v0.3.1/fclone-v0.3.1-linux-amd64.zip | unzip -o -j fclone*.zip -d /usr/bin/ | rm fclone*.zip | sudo chmod 0755 /usr/bin/fclone

    - name: unzip
      run: |
        sudo unzip -P $password sa.zip -d /
        sudo unzip -P $password rclone.zip -d /home/runner/.config/rclone/
   
    - name: SSH connection to Actions
      uses: hunter-sn/debugger-action@master
      if: env.SSH_ACTIONS == 'true'
    
